config/routes.rb
Rails.application.routes.draw do
   
  mount SamlCamel::Engine, at: '/saml'
  
  get "administration/index"
  post "administration/expire_emails"
  
#  concern :active_scaffold_association, ActiveScaffold::Routing::Association.new
  concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
  resources :posix_users, concerns: :active_scaffold

  resources :activity_logs, concerns: :active_scaffold
  resources :users, concerns: :active_scaffold
  resources :admins, concerns: :active_scaffold
  resources :dockers, concerns: :active_scaffold

  # the controller to let users manage their posix attributes
  get "posix/index"
  post "posix/update"

  get "group/index" 
   
  # report on how many containers are in use, free, or powered_down
  get "container_utilization" => "container_utilization#index"
  
  # report on hourly activity
  get "hourly_activity" => "hourly_activity#index"
  

  get 'logo'=>'logo#index'
  get 'information'=>'information#index'
  get 'incommon_login/*path'=>'information#incommon_login'
  get 'information/user_wayf/*path'=>'information#user_wayf'

  # WAYF hack for InCommon
  get 'davidson_login/*path' => 'information#davidson_login'
  get 'duke_login/*path' => 'information#duke_login'
  get 'elon_login/*path' => 'information#elon_login'
  get 'nccu_login/*path' => 'information#nccu_login'

  # bilateral federation with UNC Willmington
  get 'uncw_login/*path' => 'information#uncw_login'
 
  get 'home/index'
  get 'home/login'
  get 'home/logged_in_index', as: 'logged_in_index'  
  get 'home/search'
  get 'home/noaccess', as: :no_access
  get 'home/logout'
  
  root to: 'information#index'
   
  
  get "container_provision" =>"container_provision#index"
  get "container_provision" => "container_provision#index"
  post "/container_provision/expire_all"  
  post "/container_provision/delete_expired"  
  post "/container_provision/expire_emails" 

  resources :containers
  get "containers" =>"containers#index"
  get "containers/:id/show_panel" =>"containers#show_panel"
  get '/containers/renew', :to => 'containers#renew',  :as =>"containers_renew"  
      
  match '/containers/rstudio', :to => 'containers#rstudio', :via => :get, :as =>"containers_rstudio"  
  match '/containers/nccu-rstudio', :to => 'containers#nccu-rstudio', :via => :get, :as =>"containers_nccu-rstudio"  
  match '/containers/davidson-csc-110-0', :to => 'containers#davidson-csc-110-0', :via => :get, :as =>"containers_davidson-csc-110-0"  
  match '/containers/davidson-pol-182-a', :to => 'containers#davidson-pol-182-a', :via => :get, :as =>"containers_davidson-pol-182-a"  
  match '/containers/jupyter/*redirect', :to => 'containers#jupyter', :via => :get, :as =>"containers_jupyter"  
  match '/containers/pyroot/*redirect', :to => 'containers#pyroot', :via => :get, :as =>"containers_pyroot"  
  match '/containers/nccu-jupyter/*redirect', :to => 'containers#nccu-jupyter', :via => :get, :as =>"containers_nccu-jupyter"  
  match '/containers/davidson-mat-315-0/*redirect', :to => 'containers#davidson-mat-315-0', :via => :get, :as =>"containers_davidson-mat-315-0"  
  match '/containers/pytorch', :to => 'containers#pytorch', :via => :get, :as =>"containers_pytorch"  
  match '/containers/nccu-pytorch', :to => 'containers#nccu-pytorch', :via => :get, :as =>"containers_nccu-pytorch"  
  match '/containers/davidson-vscode', :to => 'containers#davidson-vscode', :via => :get, :as =>"containers_davidson-vscode"  
  match '/containers/knime', :to => 'containers#knime', :via => :get, :as =>"containers_knime"  
 
     
  match '/containers/restart_rstudio', :to => 'containers#restart', :via => :get, :as =>"containers_restart_rstudio"  
  match '/containers/restart_nccu-rstudio', :to => 'containers#restart', :via => :get, :as =>"containers_restart_nccu-rstudio"  
  match '/containers/restart_davidson-csc-110-0', :to => 'containers#restart', :via => :get, :as =>"containers_restart_davidson-csc-110-0"  
  match '/containers/restart_davidson-pol-182-a', :to => 'containers#restart', :via => :get, :as =>"containers_restart_davidson-pol-182-a"  
  match '/containers/restart_jupyter', :to => 'containers#restart', :via => :get, :as =>"containers_restart_jupyter"
  match '/containers/restart_pyroot', :to => 'containers#restart', :via => :get, :as =>"containers_restart_pyroot"
  match '/containers/restart_nccu-jupyter', :to => 'containers#restart', :via => :get, :as =>"containers_restart_nccu-jupyter"
  match '/containers/restart_davidson-mat-315-0', :to => 'containers#restart', :via => :get, :as =>"containers_restart_davidson-mat-315-0"
  match '/containers/restart_pytorch', :to => 'containers#restart', :via => :get, :as =>"containers_restart_pytorch"
  match '/containers/restart_nccu-pytorch', :to => 'containers#restart', :via => :get, :as =>"containers_restart_nccu-pytorch"
  match '/containers/restart_davidson-vscode', :to => 'containers#restart', :via => :get, :as =>"containers_restart_davidson-vscode"
  match '/containers/restart_knime', :to => 'containers#restart', :via => :get, :as =>"containers_restart_knime"
     
 
  match '/containers/requestrestart_rstudio', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_rstudio"  
  match '/containers/requestrestart_nccu-rstudio', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_nccu-rstudio"  
  match '/containers/requestrestart_davidson-csc-110-0', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_davidson-csc-110-0"  
  match '/containers/requestrestart_davidson-pol-182-a', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_davidson-pol-182-a"  
  match '/containers/requestrestart_jupyter', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_jupyter"  
  match '/containers/requestrestart_pyroot', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_pyroot"  
  match '/containers/requestrestart_nccu-jupyter', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_nccu-jupyter"  
  match '/containers/requestrestart_davidson-mat-315-0', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_davidson-mat-315-0"  
  match '/containers/requestrestart_pytorch', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_pytorch"  
  match '/containers/requestrestart_nccu-pytorch', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_nccu-pytorch"  
  match '/containers/requestrestart_davidson-vscode', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_davidson-vscode"  
  match '/containers/requestrestart_knime', :to => 'containers#requestrestart', :via => :get, :as =>"containers_requestrestart_knime"  
  
    
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController

  before_action :login_required
  before_action :set_user  #If they have logged in

  before_action :use_unsafe_params, only: [:show]

  def params
    @_dangerous_params || super
  end

require 'rest_client'
require 'net/ssh'

  def scan_for_user_containers( this_netid )
    this_user_app_reservations = Docker.current_reservations( this_netid )
    this_user_app_available = Docker.available_to_reserve( this_netid )
    return this_user_app_reservations, this_user_app_available       
  end
     
  def index
    @user = User.find session[:current_user_id]
    @the_reservations, @the_apps_available = scan_for_user_containers(@user.netid)
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  
  def show_panel
    @user = User.find session[:current_user_id]
    # @the_reservations = Docker.current_reservations(@user.netid)
    @panel_reservation = Docker.specific_reservation(@user.netid, params[:id])
    respond_to do |format|
      format.html 
    end
  end

  def renew
    user = User.find session[:current_user_id]
    containertype = params[:containertype]
    
    expired_instance = Docker.find_by_netid_and_appname(user.netid, containertype) 
    expired_instance.expired = false
    expired_instance.save

    # the same weird problem (in production only) where Rails is not generating a valid WHERE clause
    # when we call save on the instance is happening here and in the show method.  
    # I am again resorting to updating the record via my own SQL statement.
    # here is what was not working: 
    #         
    #          expired_instance.save
    # 
    # to avoid this, get a connection to the database, and sent it some SQL the old fashioned way 
    #
    #db_connection = ActiveRecord::Base.connection
    #db_connection.execute("UPDATE dockers SET expired = FALSE, updated_at = '#{Time.now.utc}' WHERE dockers.id = #{expired_instance.id}")

    ActivityLog.log(session[:current_user_id], 'Docker renew',"Docker: #{user.netid} renewed #{containertype} at #{expired_instance.host}:#{expired_instance.port}" )                
  end
  
    
  def show
    user = User.find(session[:current_user_id])
    # container_type = request.path.split("/").last
    #
    # to accomodate the path appendix for jupyter git_pull we need to be careful to get the right type
    #
#    puts("********** #{request.original_url} ***********")
#    puts request.params.inspect
    container_type = request.path.split('/containers/')[1].split('/')[0]
    if ((container_type == 'requestrestart_rstudio') ||
        (container_type == 'requestrestart_nccu-rstudio') ||
        (container_type == 'requestrestart_davidson-csc-110-0') ||
        (container_type == 'requestrestart_davidson-pol-182-a') ||
        (container_type == 'requestrestart_pytorch') ||
        (container_type == 'requestrestart_nccu-pytorch') ||
        (container_type == 'requestrestart_davidson-vscode') ||
        (container_type == 'requestrestart_knime') ||
        (container_type == 'requestrestart_jupyter') ||
        (container_type == 'requestrestart_pyroot') ||
        (container_type == 'requestrestart_nccu-jupyter') ||
        (container_type == 'requestrestart_davidson-mat-315-0')) then
      self.requestrestart
    elsif ((container_type == 'restart_rstudio') ||
           (container_type == 'restart_nccu-rstudio') ||
           (container_type == 'restart_davidson-csc-110-0') ||
           (container_type == 'restart_davidson-pol-182-a') ||
           (container_type == 'restart_pytorch') ||
           (container_type == 'restart_nccu-pytorch') ||
           (container_type == 'restart_davidson-vscode') ||
           (container_type == 'restart_knime') ||
           (container_type == 'restart_jupyter') ||
           (container_type == 'restart_pyroot') ||
           (container_type == 'restart_nccu-jupyter') ||
           (container_type == 'restart_davidson-mat-315-0'))
      self.restart
    elsif container_type == 'renew' then
      self.renew
    elsif container_type == 'download_rdp' then
      self.download_rdp
    else
      @first_visit = true
      reserved_instance = Docker.where("netid = ? and lower(appname) = ?", user.netid, container_type).first
      if reserved_instance.nil? then # they have never reserved an instance
        new_instance = Docker.find_by_netid_and_appname('', container_type)
        if new_instance.nil? then 
            logger.error "Failed to reserve Docker #{container_type} instance for user: #{user.netid}"
            flash[:error] = "ERROR: Cannot find an unused Docker container for #{container_type}"
            redirect_to "/containers" and return
        else
          # reserve this instance
          #
          # there is a weird problem (in production only) where Rails is not generating a valid WHERE clause
          # when we call save on the new_instance. After spending enough time to convince myself I am not going
          # to figure this out, I am resorting to updating the record via my own SQL statement.
          # here is what was not working: 
          #         
          #          new_instance.save
          # 
          # to avoid this, get a connection to the database, and sent it some SQL the old fashioned way 
          # 
          new_instance.netid = user.netid
          new_instance.save
          #db_connection = ActiveRecord::Base.connection
          #db_connection.execute("UPDATE dockers SET netid = '#{new_instance.netid}', updated_at = '#{Time.now.utc}' WHERE dockers.id = #{new_instance.id}")
          
          @docker_host = new_instance.host
          @docker_port = new_instance.port
          @docker_guest_pw = new_instance.pw  
          ActivityLog.log(session[:current_user_id], 'Docker containers',"Docker: #{user.netid} reserved #{container_type} at #{@docker_host}:#{@docker_port}" )                
          flash[:error] = "Reserved a container for #{container_type} -- to start a new session, click on the #{container_type} link in the list below."
          redirect_to "/containers" and return
        end
      else #send them to the instance they previously reserved
        @first_visit = false
        @docker_host = reserved_instance.host
        @docker_port = reserved_instance.port
        @docker_guest_pw = reserved_instance.pw    
      end 
      if container_type == 'rstudio'           
        # no longer will be use RStudio's hack-o-rama Javascript public key crypto on a form
        # instead we will  use an Nginx auth_proxy to check to port and pw and decide if we should let the user in
        #@docker_host_public_key = RestClient.get( "https://#{@docker_host}:#{@docker_port}/auth-public-key")
      elsif container_type == 'nccu-rstudio'           
        # no longer will be use RStudio's hack-o-rama Javascript public key crypto on a form
        # instead we will  use an Nginx auth_proxy to check to port and pw and decide if we should let the user in
        #@docker_host_public_key = RestClient.get( "https://#{@docker_host}:#{@docker_port}/auth-public-key")
      elsif container_type == 'davidson-csc-110-0'           
        # no longer will be use RStudio's hack-o-rama Javascript public key crypto on a form
        # instead we will  use an Nginx auth_proxy to check to port and pw and decide if we should let the user in
        #@docker_host_public_key = RestClient.get( "https://#{@docker_host}:#{@docker_port}/auth-public-key")
      elsif container_type == 'davidson-pol-182-a'           
        # no longer will be use RStudio's hack-o-rama Javascript public key crypto on a form
        # instead we will  use an Nginx auth_proxy to check to port and pw and decide if we should let the user in
        #@docker_host_public_key = RestClient.get( "https://#{@docker_host}:#{@docker_port}/auth-public-key")
      elsif container_type == 'pytorch'
        # Pytorch notebook-specific code here 
      elsif container_type == 'nccu-pytorch'
        # Pytorch notebook-specific code here 
        # to accomodate git-pull and other hacks supported by jupyterhub
        if params[:redirect].nil? then
          @pathappendix = "?next=%2Flab"
        else
          # tack the user-redirect info onto the tail end of the path
          @pathappendix = "?next=" + request.original_url.split('pytorch?redirect=')[1]
        end
#        puts("---------- #{@pathappendix} ----------")
      elsif container_type == 'davidson-vscode'
        # VSCode notebook-specific code here 
      elsif container_type == 'knime'
        # Knime notebook-specific code here 
      elsif container_type == 'jupyter' then
        # jupyter/iPython notebook-specific code here 
        # to accomodate git-pull and other hacks supported by jupyterhub
        if params[:redirect].nil? then
          @pathappendix = "?next=%2Flab"
        else
          # tack the user-redirect info onto the tail end of the path
          @pathappendix = "?next=" + request.original_url.split('jupyter?redirect=')[1]
        end
#        puts("---------- #{@pathappendix} ----------")
      elsif container_type == 'pyroot' then
        # jupyter/iPython notebook-specific code here 
        # to accomodate git-pull and other hacks supported by jupyterhub
        if params[:redirect].nil? then
          @pathappendix = "?next=%2Flab"
        else
          # tack the user-redirect info onto the tail end of the path
          @pathappendix = "?next=" + request.original_url.split('pyroot?redirect=')[1]
        end
#        puts("---------- #{@pathappendix} ----------")
      elsif container_type == 'nccu-jupyter' then
        # jupyter/iPython notebook-specific code here 
        # to accomodate git-pull and other hacks supported by jupyterhub
        if params[:redirect].nil? then
          @pathappendix = "?next=%2Flab"
        else
          # tack the user-redirect info onto the tail end of the path

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_app.html.erb
<hr>
<b><%=this_app[:container_type]%> - <%=this_app[:container_desc]%></b>  

<% if this_app[:first_visit] %>
<p><b><%= link_to "Reserve", this_app[:app_path] %></b> a <%=this_app[:container_type]%> instance</p>
<% else %>
  <% if this_app[:app_expired] %>
     <p>
       Your <%= this_app[:container_type]%> reservation has expired - container reservations are valid for one semester. <br>
       <b>
         <%=link_to("Click here to renew your reservation",{:action=>:renew,:containertype=>this_app[:container_type]})%>
       </b>
     </p>
  <% else %>
     <p>
       <b><%= link_to "Log in", this_app[:app_path] %></b> 
       to your <%=this_app[:container_type]%> instance
     </p>
     <% if ((this_app[:container_type] == 'RStudio') ||
            (this_app[:container_type] == 'Jupyter')  ||
            (this_app[:container_type] == 'Pytorch')  ||
            (this_app[:container_type] == 'NCCU-RStudio')  ||
            (this_app[:container_type] == 'PyROOT')  ||
            (this_app[:container_type] == 'NCCU-Jupyter')  ||
            (this_app[:container_type] == 'NCCU-Pytorch')  ||
            (this_app[:container_type] == 'Davidson-CSC-110-0')  ||
            (this_app[:container_type] == 'Davidson-POL-182-A')  ||
            (this_app[:container_type] == 'Davidson-MAT-315-0')  ||
            (this_app[:container_type] == 'Davidson-VSCode')  ||
            (this_app[:container_type] == 'Knime'))

      %>
       <p>
       If you are unable to connect to your <%=this_app[:container_type]%> environment your can 
	             <b><%= link_to "request a restart", this_app[:app_requestrestart_path]  %></b>.
       <p>
     <% end %>
  <% end %>
<% end %>

app/views/containers/_buttons.html.haml
#message-area

.vm-manage-buttons#nav
  .btn-group
    - if a_container[:app_expired]
      = link_to a_container[:app_renew_path], id: 'renew', class: 'duke-btn duke-btn-default', role: 'button' do
        %span.glyphicon.glyphicon-off
        %span.glyphicon-class
          Renew Reservation  
    - else
      = link_to a_container[:app_path], id: 'Login', class: 'duke-btn duke-btn-default', role: 'button' do
        %span.glyphicon.glyphicon-off
        %span.glyphicon-class
          Login  
    &nbsp
    = link_to a_container[:app_requestrestart_path], id: 'requestrestart', class: 'duke-btn ', role: 'button' do
      %span.glyphicon.glyphicon-off
      %span.glyphicon-class
        Request Restart  
    &nbsp

app/views/containers/_detailed_available_reservation_bar.html.haml
.col-sm-4
  .panel.panel-default
    .panel-heading
      %h3.panel-title Reservations available 
    .panel-body
      - if @current_user
        =render 'containers/detailed_available_logged_in_reservation'
      
      - else
        =render 'containers/not_logged_in_reservation'

app/views/containers/_not_logged_in_reservation.html.haml
%p 
  Log in with your NetID to see all of your reserved resources
%div{style: "text-align:center;margin:auto;"}
  = button_to('Log in', home_login_path, method: :get, class: 'duke-btn duke-btn-default')

app/views/containers/jupyter.html.erb
<h2>Jupyter</h2>
<div id='wrapper'>

<p><h3>Jupyter login referral page</h3><br><b>If your web browser asks if it is OK to submit this form, say yes</b></p>

<script type="text/javascript">

function submitRealForm() {
  document.getElementById('password_input').value = "<%=@docker_guest_pw%>";
  document.realform.submit();
}
</script>


<form action="https://<%=@docker_host%>:<%=@docker_port%>/login<%=@pathappendix%>" name="realform" method="POST">
   <input type="hidden" name="password" id="password_input" value="0"/>
</form>

<script type="text/javascript">
window.onload=submitRealForm()
</script>

app/views/containers/knime.html.erb
<h2>Knime</h2>
<div id='wrapper'>

<p><h3>noVNC login referral page</h3><br><b>If your web browser asks if it is OK to submit this form, say yes</b></p>

<script type="text/javascript">
function openVNCwindow() {
  window.location.replace("https://<%=@docker_host%>:<%=@docker_port%>/vnc.html?encrypt=1&autoconnect=1&password=<%=@docker_guest_pw%>&port=<%=@docker_port%>&resize=remote")
}
</script>

<script type="text/javascript">
window.onload=openVNCwindow()
</script>

app/views/containers/nccu-rstudio.html.erb
<h2>NCCU-RStudio</h2>
<div id='wrapper'>

<div id='message-area'></div>
  <div class='vm-manage-buttons' id='nav'>
    <div class='btn-group'>
      <a id="Start" class="duke-btn duke-btn-default" role="button" onclick="windowOpen()"><span class='glyphicon glyphicon-off'></span>
        <span class='glyphicon-class'>
        Start
        </span>
      </a>&nbsp
  </div>
</div>
<p><b>Click the start button to launch your session</b>
</p>


<script type="text/javascript">
  var Window;

  function windowOpen() {
    var wnd = window.open("https://<%=@docker_host%>:<%=@docker_port%>/auth/?ngxtndotoken=<%=@docker_guest_pw%>","_blank");
    setTimeout(function() {
      wnd.close();
      var wnd2 = window.location.replace("https://<%=@docker_host%>:<%=@docker_port%>/");
    }, 1000);
    return false;
}
</script>

app/views/containers/pyroot.html.erb
<h2>PyROOT</h2>
<div id='wrapper'>

<p><h3>Jupyter login referral page</h3><br><b>If your web browser asks if it is OK to submit this form, say yes</b></p>

<script type="text/javascript">

function submitRealForm() {
  document.getElementById('password_input').value = "<%=@docker_guest_pw%>";
  document.realform.submit();
}
</script>


<form action="https://<%=@docker_host%>:<%=@docker_port%>/login<%=@pathappendix%>" name="realform" method="POST">
   <input type="hidden" name="password" id="password_input" value="0"/>
</form>

<script type="text/javascript">
window.onload=submitRealForm()
</script>

app/views/containers/pytorch.html.erb
<h2>Pytorch</h2>
<div id='wrapper'>

<p><h3>Pytorch login referral page</h3><br><b>If your web browser asks if it is OK to submit this form, say yes</b></p>

<script type="text/javascript">

function submitRealForm() {
  document.getElementById('password_input').value = "<%=@docker_guest_pw%>";
  document.realform.submit();
}
</script>


<form action="https://<%=@docker_host%>:<%=@docker_port%>/login?next=%2Flab" name="realform" method="POST">
   <input type="hidden" name="password" id="password_input" value="0"/>
</form>

<script type="text/javascript">
window.onload=submitRealForm()
</script>

app/views/containers/requestrestart_nccu-pytorch.html.erb
<h2>Restart NCCU-Pytorch</h2>
<div id='wrapper'>
<p>
If you are having trouble connecting to your NCCU-Pytorch environment<br>
you should close all web browser windows, restart your web browser<br> 
and try connecting again.
</p><p>
As a last resort, you can restart NCCU-Pytorch. </p><p>
<b><i>WARNING: any work you have not saved will be lost during the restart.</i></b></p><p>
To restart NCCU-Pytorch <b><%=link_to "click here", @restart_container_path %>
</p>

app/views/containers/requestrestart_nccu-rstudio.html.erb
<h2>Restart NCCU-RStudio</h2>
<div id='wrapper'>
<p>
If you are having trouble connecting to your NCCU-RStudio environment<br>
you should close all web browser windows, restart your web browser<br> 
and try connecting again.
</p><p>
As a last resort, you can restart NCCU-RStudio. </p><p>
<b><i>WARNING: any work you have not saved will be lost during the restart.</i></b></p><p>
To restart NCCU-RStudio <b><%=link_to "click here", @restart_container_path %>
</p>

app/views/containers/restart_davidson-mat-315-0.html.erb
<h2>Restarting Davidson-MAT-315-0</h2>
<div id='wrapper'>
<p>
	<% if @restart_error == nil %>
	   Your container has been restarted. <br>
	   Go to the <%= link_to "Containers page", "/containers" %> and select Davidson-MAT-315-0 to start a new session. 
	<% else %>
	  <%=@restart_error%> 
	<% end %>
</p>

app/views/containers/restart_davidson-vscode.html.erb
<h2>Restarting Davidson-VSCode</h2>
<div id='wrapper'>
<p>
	<% if @restart_error == nil %>
	   Your container has been restarted. <br>
	   Go to the <%= link_to "Containers page", "/containers" %> and select Davidson-VSCode to start a new session. 
	<% else %>
	  <%=@restart_error%> 
	<% end %>
</p>

app/views/containers/restart_nccu-rstudio.html.erb
<h2>Restarting NCCU-RStudio</h2>
<div id='wrapper'>
<p>
	<% if @restart_error == nil %>
	   Your container has been restarted. <br>
	   Go to the <%= link_to "Containers page", "/containers" %> and select NCCU-RStudio to start a new session. 
	<% else %>
	  <%=@restart_error%> 
	<% end %>
</p>